In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('social_media_vs_productivity.csv')

In [3]:
df.head()

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060

In [4]:
df["user_id"] = pd.Series(range(1,len(df)+1))
dim_gender = df[["gender"]].drop_duplicates().reset_index(drop=True)
dim_gender["gender_id"] = dim_gender.index +1
dim_gender = dim_gender[["gender_id","gender"]]
dim_gender.to_csv("dim_gender.csv",index=False)
dim_gender

   gender_id  gender
0          1    Male
1          2  Female
2          3   Other

In [ ]:
print(df.columns)

Index(['age', 'gender', 'job_type', 'daily_social_media_time',
       'social_platform_preference', 'number_of_notifications',
       'work_hours_per_day', 'perceived_productivity_score',
       'actual_productivity_score', 'stress_level', 'sleep_hours',
       'screen_time_before_sleep', 'breaks_during_work', 'uses_focus_apps',
       'has_digital_wellbeing_enabled', 'coffee_consumption_per_day',
       'days_feeling_burnout_per_month', 'weekly_offline_hours',
       'job_satisfaction_score', 'user_id'],
      dtype='object')

In [5]:
df= df.merge(dim_gender,on="gender",how="left")
df=df.drop(columns=["gender"])
df.head(1)

,age,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,user_id,gender_id
0,56,Unemployed,4.18094,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688,1,1

In [6]:
dim_job_type = df[["job_type"]].drop_duplicates().reset_index(drop=True)
dim_job_type["job_type_id"] = dim_job_type.index + 1
dim_job_type = dim_job_type[["job_type_id", "job_type"]]
dim_job_type.to_csv("dim_job_type.csv", index=False)
df= df.merge(dim_job_type,on="job_type",how="left")
df.drop(columns=["job_type"], inplace=True)
dim_job_type

   job_type_id    job_type
0            1  Unemployed
1            2      Health
2            3     Finance
3            4          IT
4            5   Education
5            6     Student

In [7]:
df.head(1)

,age,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,user_id,gender_id,job_type_id
0,56,4.18094,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688,1,1,1

In [8]:
def categorize_age(age):
    if age < 20:
        return 'Youth (<20)'
    elif age < 30:
        return 'Young Adult (20-29)'
    elif age < 40:
        return 'Adult (30-39)'
    elif age < 50:
        return 'Middle-Aged (40-49)'
    else:
        return 'Senior (50+)'

df['age_group'] = df['age'].apply(categorize_age)

df

,age,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,...,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,user_id,gender_id,job_type_id,age_group
0,56,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,...,False,False,4,11,21.927072,6.336688,1,1,1,Senior (50+)
1,46,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,...,True,True,2,25,0.000000,3.412427,2,1,2,Middle-Aged (40-49)
2,32,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,...,True,False,3,17,10.322044,2.474944,3,1,3,Adult (30-39)
3,60,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,...,False,False,0,4,23.876616,1.733670,4,2,1,Senior (50+)
4,25,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,...,False,True,1,30,10.653519,9.693060,5,1,4,Young Adult (20-29)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,5.480462,1.412655,...,False,False,4,5,21.776927,NaN,29996,2,2,Adult (30-39)
29996,39,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,3.045393,0.148936,...,False,False,1,29,4.111370,6.155613,29997,1,2,Adult (30-39)
29997,42,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,5.491520,1.224296,...,False,False,1,2,1.888315,6.285237,29998,1,5,Middle-Aged (40-49)
29998,20,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,6.816069,0.234483,...,False,False,2,9,12.511871,7.854711,29999,2,5,Young Adult (20-29)
29999,44,NaN,Twitter,70,8.069883,6.311227,5.402726,3.0,6.765248,0.993090,...,False,True,1,4,6.324954,7.388790,30000,1,1,Middle-Aged (40-49)

In [15]:
dim_age_group = df[['age_group']].drop_duplicates().reset_index(drop=True)
dim_age_group['age_group_id'] = dim_age_group.index + 1
dim_age_group = dim_age_group[['age_group_id', 'age_group']]
dim_age_group.to_csv("dim_age_group.csv", index=False)
df = df.merge(dim_age_group, on='age_group', how='left')
df.drop(['age_group'], axis=1, inplace=True)
df.head(1)

,age,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,...,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,user_id,gender_id,job_type_id,age_group_id
0,56,4.18094,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,...,False,False,4,11,21.927072,6.336688,1,1,1,1

In [18]:
dim_social_platform = df[['social_platform_preference']].drop_duplicates().reset_index(drop=True)
dim_social_platform['social_platform_id'] = dim_social_platform.index + 1
dim_social_platform = dim_social_platform[['social_platform_id', 'social_platform_preference']]
dim_social_platform.to_csv("dim_social_platform.csv", index=False)
df = df.merge(dim_social_platform, on='social_platform_preference', how='left')
df.drop(['social_platform_preference'], axis=1, inplace=True)
df.head(1)

,age,daily_social_media_time,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,...,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,user_id,gender_id,job_type_id,age_group_id,social_platform_id
0,56,4.18094,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,...,False,4,11,21.927072,6.336688,1,1,1,1,1

In [21]:
def categorize_range(val):
    if val <= 50:
        return 'Low'
    elif val <= 70:
        return 'Medium'
    else:
        return 'High'

df['notifications_category'] = df['number_of_notifications'].apply(categorize_range)
dim_notifications = df[['notifications_category']].drop_duplicates().reset_index(drop=True)
dim_notifications['notifications_category_id'] = dim_notifications.index + 1
dim_notifications = dim_notifications[['notifications_category_id', 'notifications_category']]
dim_notifications.to_csv("dim_notifications_category.csv", index=False)

df = df.merge(dim_notifications, on='notifications_category', how='left')
df.drop(['notifications_category'], axis=1, inplace=True)
df

,age,daily_social_media_time,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,...,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,user_id,gender_id,job_type_id,age_group_id,social_platform_id,notifications_category_id
0,56,4.180940,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,...,4,11,21.927072,6.336688,1,1,1,1,1,1
1,46,3.249603,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,...,2,25,0.000000,3.412427,2,1,2,2,2,1
2,32,NaN,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,...,3,17,10.322044,2.474944,3,1,3,3,2,1
3,60,NaN,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,...,0,4,23.876616,1.733670,4,2,1,1,1,1
4,25,NaN,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,...,1,30,10.653519,9.693060,5,1,4,4,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,1.877297,59,10.226358,3.348512,3.465815,8.0,5.480462,1.412655,9,...,4,5,21.776927,NaN,29996,2,2,3,1,1
29996,39,4.437784,46,4.692862,8.133213,6.659294,8.0,3.045393,0.148936,3,...,1,29,4.111370,6.155613,29997,1,2,3,5,2
29997,42,17.724981,64,10.915036,8.611005,8.658912,5.0,5.491520,1.224296,10,...,1,2,1.888315,6.285237,29998,1,5,2,4,1
29998,20,3.796634,56,6.937410,7.767076,6.895583,8.0,6.816069,0.234483,1,...,2,9,12.511871,7.854711,29999,2,5,4,5,1
29999,44,NaN,70,8.069883,6.311227,5.402726,3.0,6.765248,0.993090,5,...,1,4,6.324954,7.388790,30000,1,1,2,2,1

In [22]:
median_stress = df['stress_level'].median()
df['stress_level'] = df['stress_level'].fillna(median_stress)

In [23]:
print(df.isnull().sum())

age                                  0
daily_social_media_time           2765
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score      1614
actual_productivity_score         2365
stress_level                         0
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
user_id                              0
gender_id                            0
job_type_id                          0
age_group_id                         0
social_platform_id                   0
notifications_category_id            0
dtype: int64

In [24]:
def categorize_stress(val):
    if val <= 3:
        return 'Low'
    elif val <= 7:
        return 'Medium'
    else:
        return 'High'

df['stress_category'] = df['stress_level'].apply(categorize_stress)
dim_stress = df[['stress_category']].drop_duplicates().reset_index(drop=True)
dim_stress['stress_category_id'] = dim_stress.index + 1
dim_stress = dim_stress[['stress_category_id', 'stress_category']]
dim_stress.to_csv("dim_stress_category.csv", index=False)
df = df.merge(dim_stress, on='stress_category', how='left')
df.drop(['stress_category'], axis=1, inplace=True)
df.head(1)

,age,daily_social_media_time,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,...,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score,user_id,gender_id,job_type_id,age_group_id,social_platform_id,notifications_category_id,stress_category_id
0,56,4.18094,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,...,11,21.927072,6.336688,1,1,1,1,1,1,1

In [27]:
print(len(df.columns))

23

In [30]:
df = df[[
    'user_id','age','age_group_id','gender_id', 'job_type_id',
    'daily_social_media_time','social_platform_id','number_of_notifications',
    'notifications_category_id', 'work_hours_per_day', 'perceived_productivity_score',
    'actual_productivity_score', 'stress_level', 'stress_category_id', 'sleep_hours',
    'screen_time_before_sleep', 'breaks_during_work', 'uses_focus_apps',
    'has_digital_wellbeing_enabled', 'coffee_consumption_per_day',
    'days_feeling_burnout_per_month', 'weekly_offline_hours',
    'job_satisfaction_score'
]]
df

,user_id,age,age_group_id,gender_id,job_type_id,daily_social_media_time,social_platform_id,number_of_notifications,notifications_category_id,work_hours_per_day,...,stress_category_id,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,1,56,1,1,1,4.180940,1,61,1,6.753558,...,1,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,2,46,2,1,2,3.249603,2,59,1,9.169296,...,1,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,3,32,3,1,3,NaN,2,57,1,7.910952,...,1,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,4,60,1,2,1,NaN,1,59,1,6.355027,...,1,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,5,25,4,1,4,NaN,3,66,1,6.214096,...,1,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,34,3,2,2,1.877297,1,59,1,10.226358,...,3,5.480462,1.412655,9,False,False,4,5,21.776927,NaN
29996,29997,39,3,1,2,4.437784,5,46,2,4.692862,...,3,3.045393,0.148936,3,False,False,1,29,4.111370,6.155613
29997,29998,42,2,1,5,17.724981,4,64,1,10.915036,...,1,5.491520,1.224296,10,False,False,1,2,1.888315,6.285237
29998,29999,20,4,2,5,3.796634,5,56,1,6.937410,...,3,6.816069,0.234483,1,False,False,2,9,12.511871,7.854711
29999,30000,44,2,1,1,NaN,2,70,1,8.069883,...,2,6.765248,0.993090,5,False,True,1,4,6.324954,7.388790

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   user_id                         30000 non-null  int64
 1   age                             30000 non-null  int64
 2   age_group_id                    30000 non-null  int64
 3   gender_id                       30000 non-null  int64
 4   job_type_id                     30000 non-null  int64
 5   daily_social_media_time         27235 non-null  float64
 6   social_platform_id              30000 non-null  int64
 7   number_of_notifications         30000 non-null  int64
 8   notifications_category_id       30000 non-null  int64
 9   work_hours_per_day              30000 non-null  float64
 10  perceived_productivity_score    28386 non-null  float64
 11  actual_productivity_score       27635 non-null  float64
 12  stress_level                    30000 non-null  float64
 13  stress_category_id              30000 non-null  int64
 14  sleep_hours                     27402 non-null  float64
 15  screen_time_before_sleep        27789 non-null  float64
 16  breaks_during_work              30000 non-null  int64
 17  uses_focus_apps                 30000 non-null  bool
 18  has_digital_wellbeing_enabled   30000 non-null  bool
 19  coffee_consumption_per_day      30000 non-null  int64
 20  days_feeling_burnout_per_month  30000 non-null  int64
 21  weekly_offline_hours            30000 non-null  float64
 22  job_satisfaction_score          27270 non-null  float64
dtypes: bool(2), float64(9), int64(12)
memory usage: 4.9 MB

In [32]:
print(df.isnull().sum())

user_id                              0
age                                  0
age_group_id                         0
gender_id                            0
job_type_id                          0
daily_social_media_time           2765
social_platform_id                   0
number_of_notifications              0
notifications_category_id            0
work_hours_per_day                   0
perceived_productivity_score      1614
actual_productivity_score         2365
stress_level                         0
stress_category_id                   0
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [33]:

median_value = df['daily_social_media_time'].median()
df['daily_social_media_time'] = df['daily_social_media_time'].fillna(median_value)

In [34]:
print(df.isnull().sum())

user_id                              0
age                                  0
age_group_id                         0
gender_id                            0
job_type_id                          0
daily_social_media_time              0
social_platform_id                   0
number_of_notifications              0
notifications_category_id            0
work_hours_per_day                   0
perceived_productivity_score      1614
actual_productivity_score         2365
stress_level                         0
stress_category_id                   0
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [35]:

mean_score = df['perceived_productivity_score'].mean()
df['perceived_productivity_score'] = df['perceived_productivity_score'].fillna(mean_score)

In [36]:
print(df.isnull().sum())

user_id                              0
age                                  0
age_group_id                         0
gender_id                            0
job_type_id                          0
daily_social_media_time              0
social_platform_id                   0
number_of_notifications              0
notifications_category_id            0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score         2365
stress_level                         0
stress_category_id                   0
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [37]:
print(df['actual_productivity_score'].mean())
print(df['actual_productivity_score'].median())

4.951804879665391
4.951741600417723

In [38]:
mean_val = df['actual_productivity_score'].mean()
df['actual_productivity_score'] = df['actual_productivity_score'].fillna(mean_val)

In [39]:
print(df.isnull().sum())

user_id                              0
age                                  0
age_group_id                         0
gender_id                            0
job_type_id                          0
daily_social_media_time              0
social_platform_id                   0
number_of_notifications              0
notifications_category_id            0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score            0
stress_level                         0
stress_category_id                   0
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [40]:
print(df['sleep_hours'].min())
print(df['sleep_hours'].max())

3.0
10.0

In [41]:
print(df['sleep_hours'].mean())
print(df['sleep_hours'].median())
print(df['sleep_hours'].mode())

6.500247461760461
6.4983398982218095
0    10.0
Name: sleep_hours, dtype: float64

In [49]:
mean_sleep = df['sleep_hours'].mean()
df['sleep_hours'] = df['sleep_hours'].fillna(mean_sleep)

In [42]:
print(df.isnull().sum())

user_id                              0
age                                  0
age_group_id                         0
gender_id                            0
job_type_id                          0
daily_social_media_time              0
social_platform_id                   0
number_of_notifications              0
notifications_category_id            0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score            0
stress_level                         0
stress_category_id                   0
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [43]:
print(df['screen_time_before_sleep'].min())
print(df['screen_time_before_sleep'].max())
print('-----------------------------------')
print(df['screen_time_before_sleep'].mean())
print(df['screen_time_before_sleep'].median())
print(df['screen_time_before_sleep'].mode())

0.0
3.0
-----------------------------------
1.0255681548961753
1.0061586763775965
0    0.0
Name: screen_time_before_sleep, dtype: float64

In [44]:
mean_screen_time = df['screen_time_before_sleep'].mean()
df['screen_time_before_sleep'] = df['screen_time_before_sleep'].fillna(mean_screen_time)

In [45]:
print(df.isnull().sum())

user_id                              0
age                                  0
age_group_id                         0
gender_id                            0
job_type_id                          0
daily_social_media_time              0
social_platform_id                   0
number_of_notifications              0
notifications_category_id            0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score            0
stress_level                         0
stress_category_id                   0
sleep_hours                       2598
screen_time_before_sleep             0
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [46]:
print(df['job_satisfaction_score'].min())
print(df['job_satisfaction_score'].max())
print('-----------------------------------')
print(df['job_satisfaction_score'].mean())
print(df['job_satisfaction_score'].median())
print(df['job_satisfaction_score'].mode())
print('-----------------------------------')
print( (df['job_satisfaction_score'].isnull().sum() / len(df)) * 100,'%')

0.0
10.0
-----------------------------------
4.96490086213521
4.951049035003638
0    0.0
Name: job_satisfaction_score, dtype: float64
-----------------------------------
9.1 %

In [47]:
mean_satisfaction = df['job_satisfaction_score'].mean()
df['job_satisfaction_score'] = df['job_satisfaction_score'].fillna(mean_satisfaction)

In [50]:
print(df.isnull().sum())

user_id                           0
age                               0
age_group_id                      0
gender_id                         0
job_type_id                       0
daily_social_media_time           0
social_platform_id                0
number_of_notifications           0
notifications_category_id         0
work_hours_per_day                0
perceived_productivity_score      0
actual_productivity_score         0
stress_level                      0
stress_category_id                0
sleep_hours                       0
screen_time_before_sleep          0
breaks_during_work                0
uses_focus_apps                   0
has_digital_wellbeing_enabled     0
coffee_consumption_per_day        0
days_feeling_burnout_per_month    0
weekly_offline_hours              0
job_satisfaction_score            0
dtype: int64

In [51]:
print(df.duplicated().sum())

0

In [52]:
df

,user_id,age,age_group_id,gender_id,job_type_id,daily_social_media_time,social_platform_id,number_of_notifications,notifications_category_id,work_hours_per_day,...,stress_category_id,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,1,56,1,1,1,4.180940,1,61,1,6.753558,...,1,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,2,46,2,1,2,3.249603,2,59,1,9.169296,...,1,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,3,32,3,1,3,3.025913,2,57,1,7.910952,...,1,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,4,60,1,2,1,3.025913,1,59,1,6.355027,...,1,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,5,25,4,1,4,3.025913,3,66,1,6.214096,...,1,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,34,3,2,2,1.877297,1,59,1,10.226358,...,3,5.480462,1.412655,9,False,False,4,5,21.776927,4.964901
29996,29997,39,3,1,2,4.437784,5,46,2,4.692862,...,3,3.045393,0.148936,3,False,False,1,29,4.111370,6.155613
29997,29998,42,2,1,5,17.724981,4,64,1,10.915036,...,1,5.491520,1.224296,10,False,False,1,2,1.888315,6.285237
29998,29999,20,4,2,5,3.796634,5,56,1,6.937410,...,3,6.816069,0.234483,1,False,False,2,9,12.511871,7.854711
29999,30000,44,2,1,1,3.025913,2,70,1,8.069883,...,2,6.765248,0.993090,5,False,True,1,4,6.324954,7.388790

In [53]:
df.to_csv('social_media_cleaned.csv', index=False)