In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('social_media_vs_productivity.csv')

In [ ]:
df.head()

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,NaN,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,NaN,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,NaN,Telegram,66,6.214096,8.868753,NaN,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             30000 non-null  int64
 1   gender                          30000 non-null  object
 2   job_type                        30000 non-null  object
 3   daily_social_media_time         27235 non-null  float64
 4   social_platform_preference      30000 non-null  object
 5   number_of_notifications         30000 non-null  int64
 6   work_hours_per_day              30000 non-null  float64
 7   perceived_productivity_score    28386 non-null  float64
 8   actual_productivity_score       27635 non-null  float64
 9   stress_level                    28096 non-null  float64
 10  sleep_hours                     27402 non-null  float64
 11  screen_time_before_sleep        27789 non-null  float64
 12  breaks_during_work              30000 non-null  int64
 13  uses_focus_apps                 30000 non-null  bool
 14  has_digital_wellbeing_enabled   30000 non-null  bool
 15  coffee_consumption_per_day      30000 non-null  int64
 16  days_feeling_burnout_per_month  30000 non-null  int64
 17  weekly_offline_hours            30000 non-null  float64
 18  job_satisfaction_score          27270 non-null  float64
dtypes: bool(2), float64(9), int64(5), object(3)
memory usage: 3.9+ MB

In [ ]:
print(df.isnull().sum())

age                                  0
gender                               0
job_type                             0
daily_social_media_time           2765
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score      1614
actual_productivity_score         2365
stress_level                      1904
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [ ]:

median_value = df['daily_social_media_time'].median()
df['daily_social_media_time'] = df['daily_social_media_time'].fillna(median_value)

In [ ]:
print(df.isnull().sum())

age                                  0
gender                               0
job_type                             0
daily_social_media_time              0
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score      1614
actual_productivity_score         2365
stress_level                      1904
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [ ]:

mean_score = df['perceived_productivity_score'].mean()
df['perceived_productivity_score'] = df['perceived_productivity_score'].fillna(mean_score)

In [ ]:
print(df.isnull().sum())

age                                  0
gender                               0
job_type                             0
daily_social_media_time              0
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score         2365
stress_level                      1904
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [ ]:
print(df['actual_productivity_score'].mean())
print(df['actual_productivity_score'].median())

4.951804879665391
4.951741600417723

In [ ]:
mean_val = df['actual_productivity_score'].mean()
df['actual_productivity_score'] = df['actual_productivity_score'].fillna(mean_val)

In [ ]:
print(df.isnull().sum())

age                                  0
gender                               0
job_type                             0
daily_social_media_time              0
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score            0
stress_level                      1904
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [ ]:
print(df['stress_level'].mean())
print(df['stress_level'].median())
print(df['stress_level'].mode())

5.514058940774487
6.0
0    3.0
Name: stress_level, dtype: float64

In [ ]:
median_stress = df['stress_level'].median()
df['stress_level'] = df['stress_level'].fillna(median_stress)

In [ ]:
print(df.isnull().sum())

age                                  0
gender                               0
job_type                             0
daily_social_media_time              0
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score            0
stress_level                         0
sleep_hours                       2598
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [ ]:
print(df['sleep_hours'].min())
print(df['sleep_hours'].max())

3.0
10.0

In [ ]:
print(df['sleep_hours'].mean())
print(df['sleep_hours'].median())
print(df['sleep_hours'].mode())

6.500247461760461
6.4983398982218095
0    10.0
Name: sleep_hours, dtype: float64

In [ ]:
mean_sleep = df['sleep_hours'].mean()
df['sleep_hours'] = df['sleep_hours'].fillna(mean_sleep)

In [ ]:
print(df.isnull().sum())

age                                  0
gender                               0
job_type                             0
daily_social_media_time              0
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score            0
stress_level                         0
sleep_hours                          0
screen_time_before_sleep          2211
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [ ]:
print(df['screen_time_before_sleep'].min())
print(df['screen_time_before_sleep'].max())
print('-----------------------------------')
print(df['screen_time_before_sleep'].mean())
print(df['screen_time_before_sleep'].median())
print(df['screen_time_before_sleep'].mode())

0.0
3.0
-----------------------------------
1.0255681548961753
1.0061586763775965
0    0.0
Name: screen_time_before_sleep, dtype: float64

In [ ]:
mean_screen_time = df['screen_time_before_sleep'].mean()
df['screen_time_before_sleep'] = df['screen_time_before_sleep'].fillna(mean_screen_time)

In [ ]:
print(df.isnull().sum())

age                                  0
gender                               0
job_type                             0
daily_social_media_time              0
social_platform_preference           0
number_of_notifications              0
work_hours_per_day                   0
perceived_productivity_score         0
actual_productivity_score            0
stress_level                         0
sleep_hours                          0
screen_time_before_sleep             0
breaks_during_work                   0
uses_focus_apps                      0
has_digital_wellbeing_enabled        0
coffee_consumption_per_day           0
days_feeling_burnout_per_month       0
weekly_offline_hours                 0
job_satisfaction_score            2730
dtype: int64

In [ ]:
print(df['job_satisfaction_score'].min())
print(df['job_satisfaction_score'].max())
print('-----------------------------------')
print(df['job_satisfaction_score'].mean())
print(df['job_satisfaction_score'].median())
print(df['job_satisfaction_score'].mode())
print('-----------------------------------')
print( (df['job_satisfaction_score'].isnull().sum() / len(df)) * 100,'%')

0.0
10.0
-----------------------------------
4.96490086213521
4.951049035003638
0    0.0
Name: job_satisfaction_score, dtype: float64
-----------------------------------
9.1 %

In [ ]:
mean_satisfaction = df['job_satisfaction_score'].mean()
df['job_satisfaction_score'] = df['job_satisfaction_score'].fillna(mean_satisfaction)

In [ ]:
print(df.isnull().sum())

age                               0
gender                            0
job_type                          0
daily_social_media_time           0
social_platform_preference        0
number_of_notifications           0
work_hours_per_day                0
perceived_productivity_score      0
actual_productivity_score         0
stress_level                      0
sleep_hours                       0
screen_time_before_sleep          0
breaks_during_work                0
uses_focus_apps                   0
has_digital_wellbeing_enabled     0
coffee_consumption_per_day        0
days_feeling_burnout_per_month    0
weekly_offline_hours              0
job_satisfaction_score            0
dtype: int64

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
df

,age,gender,job_type,daily_social_media_time,social_platform_preference,number_of_notifications,work_hours_per_day,perceived_productivity_score,actual_productivity_score,stress_level,sleep_hours,screen_time_before_sleep,breaks_during_work,uses_focus_apps,has_digital_wellbeing_enabled,coffee_consumption_per_day,days_feeling_burnout_per_month,weekly_offline_hours,job_satisfaction_score
0,56,Male,Unemployed,4.180940,Facebook,61,6.753558,8.040464,7.291555,4.0,5.116546,0.419102,8,False,False,4,11,21.927072,6.336688
1,46,Male,Health,3.249603,Twitter,59,9.169296,5.063368,5.165093,7.0,5.103897,0.671519,7,True,True,2,25,0.000000,3.412427
2,32,Male,Finance,3.025913,Twitter,57,7.910952,3.861762,3.474053,4.0,8.583222,0.624378,0,True,False,3,17,10.322044,2.474944
3,60,Female,Unemployed,3.025913,Facebook,59,6.355027,2.916331,1.774869,6.0,6.052984,1.204540,1,False,False,0,4,23.876616,1.733670
4,25,Male,IT,3.025913,Telegram,66,6.214096,8.868753,4.951805,7.0,5.405706,1.876254,1,False,True,1,30,10.653519,9.693060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,34,Female,Health,1.877297,Facebook,59,10.226358,3.348512,3.465815,8.0,5.480462,1.412655,9,False,False,4,5,21.776927,4.964901
29996,39,Male,Health,4.437784,Instagram,46,4.692862,8.133213,6.659294,8.0,3.045393,0.148936,3,False,False,1,29,4.111370,6.155613
29997,42,Male,Education,17.724981,TikTok,64,10.915036,8.611005,8.658912,5.0,5.491520,1.224296,10,False,False,1,2,1.888315,6.285237
29998,20,Female,Education,3.796634,Instagram,56,6.937410,7.767076,6.895583,8.0,6.816069,0.234483,1,False,False,2,9,12.511871,7.854711
29999,44,Male,Unemployed,3.025913,Twitter,70,8.069883,6.311227,5.402726,3.0,6.765248,0.993090,5,False,True,1,4,6.324954,7.388790

In [ ]:
df.to_csv('social_media_cleaned.csv', index=False)

In [ ]:
from google.colab import files
files.download('social_media_cleaned.csv')